name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '* 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    with:
       java-version: '11'
       distribution: 'adopt'
       cache: maven
    - name: Starting Execution
	
      run: mvn clean install
       
